### ISSUE TITLE
How should we report ebpf support for a Linux endpoint?

### ISSUE THREAD

**Issue by nicholasberlin** [elastic/endpoint-package#229]
Options seem to be adding to the `Endpoint.capabilites` array within [metadata](https://github.com/elastic/endpoint-package/tree/master/package/endpoint#metadata) or adding something to [policy response](https://github.com/elastic/endpoint-package/tree/master/package/endpoint#policy-response)

Thoughts?

@kevinlog @tabell @ferullo

**Comment by ferullo** [comment]
Can you say more?

**Comment by nicholasberlin** [comment]
https://github.com/elastic/security-team/issues/2814 has outlined some telemetry goals of the AWP.
In particular:

```
Agent (Sensor)

    1) Number of installs of Endpoint on Linux hosts
    2) Number of installs of Endpoint on Cloud hosts i.e AWS, GCP, Azure.
    3) Distro and their versions
    4) Kernel versions
    ***  5) ebPF or kProbes ***
    6) Performance metrics so we can compare eBPF vs kProbes
    7) Agent Size
```

We are trying to understand how to get this information back in telemetry and where to store it. https://github.com/elastic/endpoint-dev/pull/10437#issuecomment-1025992121

We could add to the `Endpoint.capabilities` in a  metadata metric's message ...
```json
{
"Endpoint" : {
    "capabilities" : [
        "isolation",
        "ebpf" // <-- new
    ]}
}
```

or we could add a new endpoint configuration to a policy response metric ...
```json
{
"Endpoint" : {
    "configuration" : {
        "isolation" : true,
        "ebpf" : true // <-- new
    }
}
```

**Comment by ferullo** [comment]
@kevinlog @pzl do you have thoughts?

**Comment by ferullo** [comment]
Thinking about this more, I think we should generalize this.

It's valuable for Endpoint to report the features available on the host it is running on. From a users perspective it may not matter but Endpoint may use totally different implementations on different systems for the same purpose. Exposing what decision was made by Endpoint is useful for debugging. Even if Endpoint is not using a feature at the moment it could report what implementation it would use if that feature is enabled.

The same mindset as `Endpoint.capabilities` probably applies (this is a flexible list that will change over time). We should just also put it in `policy_response` as well as `metadata` where it is now.

Since it's not the case that _Kibana_ will care about these fields should we start a new list field that is different that `Endpoint.capabilities` or is it better to just still with a single list and accept that not every consumer (Kibana, developers, users) will care about every item in the list.

cc @fntlnz

**Comment by ferullo** [comment]
I propose we give this until Monday morning and then call it decided that Endpoint will start putting more enums in `Endpoint.capabilities` even if they aren't relevant to Kibana itself, and Endpoint will put `Endpoint.capabilities` in the `policy_response` document as well as the `metadata` document.

**Comment by ferullo** [comment]
It's decided. 😄
