### ISSUE TITLE
Add host.domain field and honor host.name ecs recommendation

### ISSUE THREAD

**Issue by Kogl1n** [elastic/endpoint-package#561]
The agent in version 8.12.2 sends events according to ecs.version 8.10.0.
The general ecs field reference in 8.10.0+ recommends host.name to be the lowercase fqdn.
But that's not the case! The events do not have a host.domain field in the first place. 
Winlog events do follow this recommendation on the other hand.

**Comment by ferullo** [comment]
Are you referring to just the Elastic Defend integration?

Are you asking for `host.name` to be a lower case FQDN or have `host.domain` added?

Under the Settings for an Agent policy there is an option to cause Agent and all integrations use FQDN rather than just the hostname for `host.name`.

![Image](https://github.com/user-attachments/assets/35c6a1a0-4c46-4baf-ae3d-2f2d51c1cf90)

**Comment by Kogl1n** [comment]
@ferullo Thank you! That's the setting we were looking for. Our lab environment was initially deployed manually. host.domain is not necessarily needed.
